---
# Make sure to check the documentation at https://goreleaser.com/
before:
  hooks:
    - go mod download
#    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -extldflags "-static" -X main.version={{.Version}} -X main.build={{.ShortCommit}} -X main.time={{.Date}} -X main.builtBy=goreleaser`
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
release:
  draft: true
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore'
...
