builds:
  - id: "awsu-linux-darwin"
    builder: prebuilt
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    goamd64:
    - v1
    prebuilt:
      path: build/awsu_{{ .Os }}_{{ .Arch }}
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: kreuzwerker
      name: homebrew-taps
      token: "{{ .Env.GORELEASER_TOKEN }}"
    homepage: "https://github.com/kreuzwerker/awsu"
    description: "It provides a convenient integration of AWS virtual MFA devices into commandline based workflows."