before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: kreuzwerker
      name: homebrew-taps
      token: "{{ .Env.GORELEASER_TOKEN }}"
    homepage: "https://github.com/kreuzwerker/awsu"
    description: "It provides a convenient integration of AWS virtual MFA devices into commandline based workflows."