name: tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  pull_request:
    types: ['opened', 'synchronize']
    paths-ignore:
      - 'README.md'
jobs:
  unit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Setup Dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -qqy libpcsclite-dev
      - name: Run tests
        run: make test