name: tests

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    types: ['opened', 'synchronize']
    paths-ignore:
      - 'README.md'
jobs:
  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Setup Dependencies
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update -q
          sudo apt-get install -qqy libpcsclite-dev
      - name: Run tests
        run: go test ./... -cover